apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ticket-reservation
  region: us-west-2
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
