services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications

  reservations:
    image: 822248934593.dkr.ecr.us-west-2.amazonaws.com/reservations:latest
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy

  auth:
    image: 822248934593.dkr.ecr.us-west-2.amazonaws.com/auth:latest
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
    depends_on:
      mongo:
        condition: service_healthy

  payments:
    image: 822248934593.dkr.ecr.us-west-2.amazonaws.com/payments:latest
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'

  notifications:
    image: 822248934593.dkr.ecr.us-west-2.amazonaws.com/notifications:latest
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/mongodb
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  mongodb:
